### ISSUE TITLE
Can I customize the reward function ? 

### ISSUE THREAD

**Issue by lyshello123** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#10]
Can I customize the reward function ?  Which code file should I modify if I can ? 
Thank you very much !

**Comment by Kyushik** [comment]
If you want to customize the reward function, you should modify the unity codes. 
I want to provide the unity code. However, it has some paid asset, so it is hard to provide. 
Can you describe the reward function? If it is not so complicated, I will try to make one.

**Comment by lyshello123** [comment]
It is very kind of you and thank you very much.
