### ISSUE TITLE
Question about ".ckpt" files

### ISSUE THREAD

**Issue by Deepak3994** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#13]
Hi,

I have downloaded the github repo and started the training process. May i know where the models are getting dumped?
I could not find any ".ckpt" files in that directory while the training was going on.

**Comment by 1moles** [comment]
“.ckpt”files are generated only after the training progress is completed.

**Comment by Kyushik** [comment]
Yes. .ckpt file is generated after all the training is finished. You can change the save rate of the model while training.

**Comment by Deepak3994** [comment]
Got the results. Thanks
