### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Malathi15** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#19]
Hi @Kyushik , I'm using Ubuntu 16.04. I have run the file Double_Dueling_image.ipynb. The Num_training = 1000000 is done but still the training is not stopped. 

When will the training stop or how can I stop the training?

Thanks in Advance

**Comment by Kyushik** [comment]
Hi! :) 
Training is finished when step is Num_start_training + Num_training.
So, if Num_start_training = 50000 and Num_training = 1000000, training is finished at step == 1050000.

**Comment by Malathi15** [comment]
@Kyushik  Thanks for your reply :)

How is the distance calculated in Double_Dueling_image.ipynb? Is that using sensor?

**Comment by Kyushik** [comment]
Yes. That is the distance which is provided by the sensor. I obtain the value using raycast in Unity.
