### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by karanchawla** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#2]
Hey I plan to use this simulator for my class project and I was wondering if the Mac version is going to be released any time soon?

Thanks for this!

**Comment by Kyushik** [comment]
Wow! Thanks for using my simulator! I will try to fix some more minor bugs and upload mac and linux version in this weekend!

**Comment by karanchawla** [comment]
Sweet thank you!
