### ISSUE TITLE
the simulation screen is stuck

### ISSUE THREAD

**Issue by xiaobaichongchongchong** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#26]
Hello, I encountered a strange problem during the development process, the simulation screen is stuck, my operating system is win7 64 bit, may I ask where the problem may occur? If I load the emulator of the previous version or use emv_name = "../environment/Planning/Windows/Planning", the picture will not freeze

**Comment by xiaobaichongchongchong** [comment]
![image](https://user-images.githubusercontent.com/29254247/78765349-76aabb80-79ba-11ea-90a3-1d61ad8c0d54.png)
I have purchased SimpleTown simple Racer

**Comment by xiaobaichongchongchong** [comment]
[20200408_170403.zip](https://github.com/MLJejuCamp2017/DRL_based_SelfDrivingCarControl/files/4449444/20200408_170403.zip)
MP4 file, looking forward to your reply

**Comment by Kyushik** [comment]
Hello. Thanks for using my simulator! Actually the screen is not stuck, it updates screen in every 100 time steps. So it looks screen is frozen, but it works fine. It reduces the graphic computation, so it makes the algorithm runs faster. If you want to change this, please change the Time scale in Academy inside Unity and build the environment as follows.
![image](https://user-images.githubusercontent.com/11716370/78772327-8d5a0e00-79cc-11ea-9611-b50f4d6785b8.png)

**Comment by xiaobaichongchongchong** [comment]
Okay, I have solved my problems with your help, thank you very much. :）
