### ISSUE TITLE
Running Simulator

### ISSUE THREAD

**Issue by RifkyYP** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#29]
![image](https://user-images.githubusercontent.com/68120605/95700928-68dc3880-0c72-11eb-88d6-b8d2d507c047.png)

do i need to install other dependencies, like unity3d, to run this simulator? because the simulator always got crash and not responding when the progress is still observing. And also do you have any idea to make the simulator running smoothly on my PC? 
btw I run this simulator with:
CPU : AMD Ryzen 5 4600H  @3.00 GHz
GPU : NVIDIA Geforce GTX 1650
Memory : 8GB

**Comment by Kyushik** [comment]
Hello. Thanks for using my simulator! The screen of the simulator is updated every 100 step for speeding up the RL calculation. After the training is finished, please change the train_mode to False. Then the screen of the simulator is updated every step and  runs smoothly.

**Comment by RifkyYP** [comment]
its' work. Thank you. Another question, does this program already supported for GPU computation or i need to set it by myself depend on my PC specification?

**Comment by Kyushik** [comment]
If you want to use GPU, you should install tensorflow-gpu. Then you can use GPU for running this program.
