### ISSUE TITLE
Questions about project

### ISSUE THREAD

**Issue by eds89** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#4]
Hello,
Is this an academic project? If so, were the results published elsewhere and where can I find the corresponding paper?

All the best,
Eduardo

**Comment by Kyushik** [comment]
Actually this simulator was made for project of Machine leaning camp Jeju 2017.
However, I am trying to write some papers using this simulator.
Even though there is no paper about this simulator, but maybe the ppt file that I presented at the camp might be helpful. You can download it from the link which is at the readme.md. 
Thank you! :smile:

**Comment by eds89** [comment]
Ok, good. I wonder where can I find the training data? What format is it
stored as?

**Comment by Kyushik** [comment]
Actually, this simulator was made for learning and testing deep reinforcement learning algorithm. It is trained online, so there is no training data.
