### ISSUE TITLE
Couldn't launch the jeju_camp environment. 

### ISSUE THREAD

**Issue by Zhousiyuhit** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#5]
Hello, I encountered some problems that "couldn't launch the jeju_camp environment."
<img width="891" alt="2018-05-08 12 36 56" src="https://user-images.githubusercontent.com/24530382/39738287-d8fd4914-52bc-11e8-9be5-3070c02c4864.png">
Maybe you can tell me how to solve this problem? Thanks~

**Comment by Kyushik** [comment]
You should write the path of environment to env_name.
In my case, environment path is ../environment/jeju_camp
so I wrote the above path to env_name

**Comment by Zhousiyuhit** [comment]
Sorry, I don’s know the environment path is python path? Or Unity path?
Siyu Zhou
—————————————————————————
Reinforcement Learning | Motion Planning
Harbin Institute of Technology School of Astronautics
Phone: 86+18845027614
Email: hitaezsy@gmail.com | 17s118203@stu.hit.edu.cn

**Comment by Zhousiyuhit** [comment]
Maybe I know it, it’s Unity path~
Siyu Zhou
—————————————————————————
Reinforcement Learning | Motion Planning
Harbin Institute of Technology School of Astronautics
Phone: 86+18845027614
Email: hitaezsy@gmail.com | 17s118203@stu.hit.edu.cn

**Comment by Kyushik** [comment]
Yeah~ you should unzip the environment file to certain path, and write the path of the file to env_path :)

**Comment by Zhousiyuhit** [comment]
Thanks very much, I have another question about the environment path~ I installed Unity on macOs, so how to find the unity environment to launch?

Siyu Zhou
—————————————————————————
Reinforcement Learning | Motion Planning
Harbin Institute of Technology School of Astronautics
Phone: 86+18845027614
Email: hitaezsy@gmail.com | 17s118203@stu.hit.edu.cn

**Comment by Kyushik** [comment]
Oh! Actually, you don't need Unity to launch the environment file. Just unzip it into some folder and set the env_path and just launch the ipynb file. However, I didn't update environment for Mac and Linux. I will upload them today!

**Comment by Zhousiyuhit** [comment]
Ok, thanks~😁
Siyu Zhou
—————————————————————————
Reinforcement Learning | Motion Planning
Harbin Institute of Technology School of Astronautics
Phone: 86+18845027614
Email: hitaezsy@gmail.com | 17s118203@stu.hit.edu.cn

**Comment by Zhousiyuhit** [comment]
I just reset the environment path, and there was another NameError that “name ‘UnityEnvironment’ is not defined.” So if you update environment for Mac and the problem can be solved?
Siyu Zhou
—————————————————————————
Reinforcement Learning | Motion Planning
Harbin Institute of Technology School of Astronautics
Phone: 86+18845027614
Email: hitaezsy@gmail.com | 17s118203@stu.hit.edu.cn

**Comment by Zhousiyuhit** [comment]
Oh, I succeed in importing the environment model, but the model is the 3Dball when I learned examples for Unity, so how can I get the "self driving car” model? Thanks~
Siyu Zhou
—————————————————————————
Reinforcement Learning | Motion Planning
Harbin Institute of Technology School of Astronautics
Phone: 86+18845027614
Email: hitaezsy@gmail.com | 17s118203@stu.hit.edu.cn

**Comment by Kyushik** [comment]
Really? It's odd..  Did you set env_path as ../environment/jeju_camp?

**Comment by Zhousiyuhit** [comment]
Oh, I just set the env_name like this:

env_name = "/Users/siyuchou/Desktop/DRL_Lab/DRL_based_SelfDrivingCarControl/SiyuZhou_3Dball”

But I think the environment zip file as you said is the safe-car model? It’s right?

Siyu Zhou
—————————————————————————
Reinforcement Learning | Motion Planning
Harbin Institute of Technology School of Astronautics
Phone: 86+18845027614
Email: hitaezsy@gmail.com | 17s118203@stu.hit.edu.cn

**Comment by Kyushik** [comment]
Yes. The link of the environment.zip file is in the readme.md. Download it and unzip it! :)

**Comment by Zhousiyuhit** [comment]
Oh, the problem continued! 
env_name = "/Users/siyuchou/Desktop/DRL_Lab/DRL_based_SelfDrivingCarControl/environment/Contents/MacOS/jeju_camp" # Name of the Unity environment binary to launch
train_mode = True # Whether to run the environment in training or inference mode
It’s right?

And I run the jupyter notebook, the error can be shown as:

---------------------------------------------------------------------------
UnityEnvironmentException                 Traceback (most recent call last)
<ipython-input-5-19bd9c6b2f7f> in <module>()
----> 1 env = UnityEnvironment(file_name=env_name)
      2 
      3 # Examine environment parameters
      4 print(str(env))
      5 

~/Desktop/DRL_Lab/DRL_based_SelfDrivingCarControl/unityagents/environment.py in __init__(self, file_name, worker_id, base_port, curriculum, seed)
     92             raise UnityEnvironmentException("Couldn't launch the {0} environment. "
     93                                             "Provided filename does not match any environments."
---> 94                                             .format(true_filename))
     95         else:
     96             logger.debug("This is the launch string {}".format(launch_string))

UnityEnvironmentException: Couldn't launch the jeju_camp environment. Provided filename does not match any environments.

Maybe I made another mistake in some steps??
Siyu Zhou
—————————————————————————
Reinforcement Learning | Motion Planning
Harbin Institute of Technology School of Astronautics
Phone: 86+18845027614
Email: hitaezsy@gmail.com | 17s118203@stu.hit.edu.cn

**Comment by Kyushik** [comment]
Oh. Okay. I uploaded my github version to 0.8! Please erase the previous version and download new version. And there will be environment folder. Unzip the environment_mac.zip into the environment folder. Then run the ipynb file. I think this can solve your problem! :smile:
