### ISSUE TITLE
question about project

### ISSUE THREAD

**Issue by 1moles** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#6]
I'm sorry for disturbing you.I'm a beginner for DRL and interested in your project.I download your project and the simulator.But I don't know how to run it successfully.Hope to get your help.Thank you.

**Comment by Kyushik** [comment]
Hello. Thanks for having interest in my project! Ask anything about my project. The process of running this project is as follows. 

1. download the github repo
2. download and unzip the simulator inside environment folder
3. open ipynb file inside RL_algorithms 
4. run the ipynb file and it's done! 

I hope it works well! 😄

**Comment by Kyushik** [comment]
Oh just download the simulator inside the environment folder! It is already unzipped!

**Comment by 1moles** [comment]
Thanks for answering my questions.There maybe some problems with my environment of this project.I plan to do it according to your method.Do I need to install CUDA and cuDNN?

**Comment by Kyushik** [comment]
You can run this code with tensorflow either CPU and GPU. However, I recommend you to run this code with GPS, because it takes long time to train this agent.
