### ISSUE TITLE
question about saved_networks

### ISSUE THREAD

**Issue by 1moles** [MLJejuCamp2017/DRL_based_SelfDrivingCarControl#8]
I run the program and simulator according to your method, set it to training mode, but the trained model cannot be saved. Num_training is 1M.But on my computer, when the number of steps is 10K, the program runs slowly.If I need to reset Num_training?The problem is that it cannot generate ckpt file.The file type it produces is different from ckpt file, such as "events.out.tfevents.1527528894" .I would like to ask if you have any good suggestions or have a trained network that i can use.Thank you so much for helping me.

**Comment by 1moles** [comment]
I have solved the problems.Thank you.

**Comment by Deepak3994** [comment]
Hi 1moles,

Did you find the solution for your problem?
Was there any .ckpt  files getting dumped?
